In [1]:
import numpy as np #넘넘파이

In [2]:
asList = [1,2,3] # 그냥 리스트 -> 대체로 많은 연산이 파이썬 리스트에서는 잘 동작하지는 않음
asArray = np.array([1,2,3]) # 1차원 벡터 -> 방향이 업슴
rowVec = np.array([[1,2,3]]) # 행벡터 -> 하나의 행이 모든 숫자를 가짐
colVec = np.array([[1], [2], [3]]) # 열벡터 -> 하나의 숫자를 가진 여러 행이 존재

print(f'asList : {np.shape(asList)}')
print(f'asArray : {np.shape(asArray)}')
print(f'rowVec : {np.shape(rowVec)}')
print(f'colVec : {np.shape(colVec)}')

asList : (3,)
asArray : (3,)
rowVec : (1, 3)
colVec : (3, 1)


In [3]:
# 두 벡터의 덧셈

v = np.array([1,2,3])
w = np.array([4,5,6])
u = np.array([7,8,9,10])

vPlusW = v + w
uPlusW = u + w # <-- 오류: 차원 불일치(ValueError: operands could not be broadcast together with shapes (4,) (3,) )

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
#열벡터에 행벡터 더하기

v = np.array([[1,2,3]]) #행벡터 
w = np.array([[10,20,30]]).T #열벡터
v+w # broadcasting 연산임
# 두 벡터의 차원과 방향이 같을때만 더할 수 있음

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
#스칼라 - 벡터 곱셈
#여기에 일반 파이썬 리스트일 경우를 곁들인

s = 2
a = [1,2,3] #list
b = np.array(a) #np array
print(a*s) #이거하면 그냥 반복임(rgrg)
print(b*s)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [6]:
#스칼라 - 벡터 덧셈
#벡터에 스칼라를 더하는 건 원래 안됨, 벡터와 스칼라는 별도의 수학적 객체이기 때문
#하지만 파이썬과 같은 수치 처리 프로그램에서는 가능(스칼라-벡터 곱셈과 유사)

s = 2
v = np.array([1,2,3])
s+v

array([3, 4, 5])

In [7]:
#벡터의 크기

v = np.array([1,2,3,4,5,6,7,8,9])
v_dim = len(v) # 수학의 차원 -> 배열의 길이
v_mag = np.linalg.norm(v) # 수학적(기하학적) 크기, 길이 또는 norm -> 유클리드 거리 공식으로 구하는듯?
print(v_dim)
print(v_mag)

# ||v|| = 1 -> 단위벡터(기하학적인 길이가 1인 벡터)
v_hat = (1/v_mag)*v #단위벡터 생성하기: 벡터 norm의 역수를 벡터에 스칼라 곱셈
print(v_hat)
print(np.linalg.norm(v_hat))


9
16.881943016134134
[0.05923489 0.11846978 0.17770466 0.23693955 0.29617444 0.35540933
 0.41464421 0.4738791  0.53311399]
0.9999999999999999


In [8]:
# 벡터 - 내적
# 아주 중요함, 아주아주중요
# 원소별로 곱하고 합함

v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
print(np.dot(v, w)) #np.dot()이 제일 간단함. 그러나 실제로 벡터-내적을 구현하지는 않음. 여러 내적으로 이루어진 행렬 곱셈을 구현한거

# 벡터에 스칼라를 곱하면 내적도 그만큼 커짐(ㅋ)
s = 10
print(np.dot(s*v,w))

70
700


In [9]:
# 내적의 분배 법칙
# a^T(b+c) = a^T B + a^T C

a = np.array([0,1,2])
b = np.array([3,5,8])
c = np.array([13,21,34])

#내적 분배 법칙
res1 = np.dot(a, b+c)
res2 = np.dot(a,b) + np.dot(a,c)
print(res1)
print(res2)

110
110


In [ ]:
# 아다마르 곱
#두 벡터의 대응되는 각 원소를 곱
#여러 스칼라를 곱할 때 편리함

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]
